### ISSUE TITLE
2.0.0 docker image segfaults / crashes seemingly on any configuration, appears to not read credentials correctly

### ISSUE THREAD

**Issue by doctorpangloss** [crazy-max/ddns-route53#186]
### Behaviour

segfault is on this line: `accessKeyID, err := utl.GetSecret(cfg.Credentials.AccessKeyID, cfg.Credentials.AccessKeyIDFile)`

I specify my AWS credentials using the bog-standard environment variables.

#### Steps to reproduce this issue

1. Migrate a `v1` config and environment variables to `v2`
2. Observe the following error:

```
{"level":"info","version":"2.0.0","time":"2020-08-05T02:50:25Z","message":"Starting ddns-route53"}

{"level":"info","time":"2020-08-05T02:50:25Z","message":"Configuration loaded from file: /etc/ddns-route53/ddns-route53.yml"}

{"level":"info","time":"2020-08-05T02:50:25Z","message":"Configuration loaded from 1 environment variables"}

panic: runtime error: invalid memory address or nil pointer dereference

[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x9a769e]


goroutine 1 [running]:

github.com/crazy-max/ddns-route53/v2/internal/app.New(0xae1659, 0xc, 0xae1659, 0xc, 0xafdda8, 0x38, 0xaf6969, 0x29, 0xb01233, 0x58, ...)

	/app/internal/app/ddnsr53.go:39 +0x3e

main.main()

	/app/cmd/main.go:82 +0x8c7

      
```

#### Expected behaviour

The application should run.

#### Actual behaviour

It segfaults compared to v1.

### Configuration

* ddns-route53 version : 2.0.0
* Platform (windows/linux) : linux 

**Working v1**

```yml
route53:
  records_set:
    - name: "*.example.com"
      type: "A"
      ttl: 300
```

```yml
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_HOSTED_ZONE_ID=${AWS_HOSTED_ZONE_ID}
      - LOG_JSON=true
      - SCHEDULE=@every 10s
```

**Crashing v2**

```yml
route53:
  recordsSet:
    - name: "*.example.com"
      type: "A"
      ttl: 300
```

```yml
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - DDNSR53_ROUTE53_HOSTEDZONEID=${AWS_HOSTED_ZONE_ID}
      - LOG_JSON=true
      - SCHEDULE=@every 10s
```

**Comment by crazy-max** [comment]
@doctorpangloss A fix is being deployed. Thanks for your input!
